repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: [--fix] 
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.16
    hooks:
      - id: uv-lock 

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run python -m pytest --cov=src --cov-report=term
        language: python
        pass_filenames: false
        additional_dependencies: 
        - pytest
        - pytest-cov